services:
  mytask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    command:
      - "uv"
      - "run"
      - "uvicorn"
      - "mytask.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "-m",
        "celery",
        "-A",
        "mytask.workers",
        "worker",
        "--loglevel=info",
      ]
    env_file:
      - .env.docker
    volumes:
      - /home/z/.bittensor:/root/.bittensor
    depends_on:
      - redis

volumes:
  redis-data:
  postgres-data:
